os:
  #- linux
  - osx

env:
  global:
    - ARTIFACTS_TARGET_PATHS="bin/zlib"
    - ARTIFACTS_BUCKET="pixelport"

install:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

script:
  - echo "test" > test.txt

after_script:
  - artifacts upload
